description: >- # this means to ignore newlines until "baseurl:"
  Ultimate Yogurt website

url: "https://www.yogurt.ai"
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include: ['_pages']